### ISSUE TITLE
feature / Jungsoyi / Board / #26

### ISSUE THREAD

**Issue by JungSoyi** [codestates-seb/seb40_main_005#26]
## Description

Board Post API 설계

## Todo

- [x] Entity와 Controller 단의 의존성 제거하기
- [x] Service 클래스를 세분화하기 -> 별도의 mapper 클래스가 필요 없어진다!
- [x] 테스트 코드 작성하기 -> OPENAPI 3.0.

## ETC
- 클라이언트에서 보드를 찔렀을 때, 어디까지 내보내야 할지? responsedto...
- SOLID 원칙 상기 
- 단일책임원칙 
- 특정 클라이언트를 위한 인터페이스 여러 개가 범용 인터페이스 하나보다 낫다
