### ISSUE TITLE
Feature/ eunbi / client 초기세팅

### ISSUE THREAD

**Issue by rachelyu1025** [codestates-seb/seb40_main_005#28]
## Description

client 폴더 내 FE팀에서 사용할 기술스택에 관련된 초기세팅을 진행한다. 

## Todo
- [x] Next.js setting
- [x] TypeScript setting
- [x] prettier setting
- [x] tailwind CSS setting
- [x] react query setting
- [x] recoil setting

## ETC
- 주의 사항 혹은 기타 내용
