### ISSUE TITLE
Fix / 데모데이 전 구현사항들에 대한 버그 수정

### ISSUE THREAD

**Issue by rachelyu1025** [codestates-seb/seb40_main_005#369]
## Description

설명을 작성해주세요.

## Todo

- [x] 공유알림 수락/거절 버튼 클릭 시 바로 적용되도록
- [ ] 파일 업로드 버그 (재업로드, 유지 문제)  
- [ ] isLoadding 적용
- [ ] 랜딩페이지 스크롤 
- [ ] 반응형 min-width 

## ETC
- 주의 사항 혹은 기타 내용
