### ISSUE TITLE
feature/랜딩페이지 레이아웃 구현

### ISSUE THREAD

**Issue by hun0613** [codestates-seb/seb40_main_005#57]
## Description

랜딩페이지에 대한 레이아웃 구성과 다양한 인터랙션 및 스크롤 애니메이션 구현

## Todo

- [x] 랜딩페이지 이미지 수집
- [x] 랜딩페이지 텍스트 배치 및 레이아웃 구현
- [ ] 스크롤 애니메이션 구현
- [x] 반응형 구현

## ETC
- 피그마의 모바일, 데스크탑, 테블릿 버전 확인하기
