### ISSUE TITLE
feature/사용설명서 페이지 레이아웃 구현

### ISSUE THREAD

**Issue by hun0613** [codestates-seb/seb40_main_005#61]
## Description

사용설명서 페이지 레이아웃 구현

## Todo

- [x] 페이지 레이아웃 구현
- [x] 스크롤 애니메이션 구현
- [x] 모션 애니메이션 구현

## ETC
- 주의 사항 혹은 기타 내용
