### ISSUE TITLE
feature/재사용_모달 레이아웃 구현

### ISSUE THREAD

**Issue by hun0613** [codestates-seb/seb40_main_005#70]
## Description

게시글 작성, 확인 모달 컨테이너 레이아웃 구현

## Todo

- [x] 컨테이너 영역 구현
- [x] onclick시 우->좌, 모바일 시 아래에서 위로 올라가는 애니메이션 구현
- [x] 반응형 구현
- [x] 컨테이너 내부에서 바로 영역 할당할 수 있도록 props처리

## ETC
- 주의 사항 혹은 기타 내용
