### ISSUE TITLE
feature/캘린더 페이지_side-bar 구현

### ISSUE THREAD

**Issue by hun0613** [codestates-seb/seb40_main_005#78]
## Description

캘린더페이지 side-bar 구현

## Todo

- [x] sidebar 레이아웃 구현
- [x] tag 컨테이너 구현
- [x] 커머스페이지 바로가기 버튼 구현
- [x] 반응형 구현

## ETC
- 주의 사항 혹은 기타 내용
